apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub

configMapGenerator:
  - name: notebook-parameters
    envs:
      - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: odh-minimal-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.odh-minimal-notebook-image-n
  - name: odh-minimal-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-n-1
  - name: odh-minimal-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-n
  - name: odh-minimal-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-n-1
  - name: odh-pytorch-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-n
  - name: odh-pytorch-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-n-1
  - name: odh-generic-data-science-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-n
  - name: odh-generic-data-science-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-n-1
  - name: odh-tensorflow-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-n
  - name: odh-tensorflow-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-n-1
  - name: odh-trustyai-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebook-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-trustyai-notebook-image-n