varReference:
- path: spec.tags[0].from.name
  kind: ImageStream
  file: minimal-notebook-imagestream.yaml
- path: spec.tags[1].from.name
  kind: ImageStream
  file: minimal-notebook-imagestream.yaml
- path: spec.tags[0].from.name
  kind: ImageStream
  file: minimal-gpu-notebook-imagestream.yaml
- path: spec.tags[1].from.name
  kind: ImageStream
  file: minimal-gpu-notebook-imagestream.yaml
- path: spec.tags[0].from.name
  kind: ImageStream
  file: pytorch-notebook-imagestream.yaml
- path: spec.tags[1].from.name
  kind: ImageStream
  file: pytorch-notebook-imagestream.yaml
- path: spec.tags[0].from.name
  kind: ImageStream
  file: generic-data-science-notebook-imagestream.yaml
- path: spec.tags[1].from.name
  kind: ImageStream
  file: generic-data-science-notebook-imagestream.yaml
- path: spec.tags[0].from.name
  kind: ImageStream
  file: tensorflow-notebook-imagestream.yaml
- path: spec.tags[1].from.name
  kind: ImageStream
  file: tensorflow-notebook-imagestream.yaml
- path: spec.tags[0].from.name
  kind: ImageStream
  file: trustyai-notebook-imagestream.yaml
