varReference:
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-minimal-notebook-image-n
- path: spec/tags[1]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-minimal-notebook-image-n-1
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-minimal-gpu-notebook-image-n
- path: spec/tags[1]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-minimal-gpu-notebook-image-n-1
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-pytorch-gpu-notebook-image-n
- path: spec/tags[1]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-pytorch-gpu-notebook-image-n-1
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-generic-data-science-notebook-image-n
- path: spec/tags[1]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-generic-data-science-notebook-image-n-1
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-tensorflow-gpu-notebook-image-n
- path: spec/tags[1]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-tensorflow-gpu-notebook-image-n-1
- path: spec/tags[0]/from/name
  kind: ImageStream
  apiGroup: image.openshift.io/v1
  name: odh-trustyai-notebook-image-n
